const constants = {
    ADD_COLOR: "ADD_COLOR",
    RATE_COLOR: "RATE_COLOR",
    REMOVE_COLOR: "REMOVE_COLOR",
    SORT_COLORS: "SORT_COLORS",
    SORTED_BY_DATE: "SORTED_BY_DATE",
    SORTED_BY_TITLE: "SORTED_BY_TITLE",
    SORTED_BY_RATING: "SORTED_BY_RATING"
}

export default constants
